version: '3.9'


x-settings: &global
  env_file:
    - .env
  environment:
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - REDIS_HOST=${REDIS_HOST}
    - REDIS_PORT=${REDIS_PORT}
    - REDIS_DB=${REDIS_DB}

services:
  db:
    container_name: simple-id-pgsql
    image: postgres:16-alpine
    restart: always
    environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
    ports:
        - ${DB_PORT}:5432
#    healthcheck:
#        test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'" ]
#        interval: 10s
#        timeout: 3s
#        retries: 3
    volumes:
        - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: simple-id-redis
    image: redis:alpine
    restart: always
    ports:
        - ${REDIS_PORT}:6379
    volumes:
        - redis_data:/data
    expose:
        - 6379

volumes:
  postgres_data:
  redis_data: